version: "3.9"
services:
  nginx-ssl:
    image: nginx-ssl
    container_name: nginx-ssl
    volumes:
     - '/var/www/html/repo:/var/www/html/repo'
     - nginx_config:/etc/nginx/conf.d
    ports:
     - "443:443" 

volumes:
  nginx_config:
    external: true
